version: '2'

services:
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
      - '2181:2181'
      - '2888:2888'
      - '3888:3888'
    volumes:
      - '/data/zookeeper:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=2
      # You have to change the IP address appropriately in the following line.
      - ZOO_SERVERS=172.1.1.1:2888:3888,0.0.0.0:2888:3888

  kafka:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    ports:
      - '9092:9092'
    volumes:
      - '/data/kafka:/bitnami/kafka'
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_NUM_PARTITIONS=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=2
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=2
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=2
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=EXTERNAL://:9092
      # You have to change the URL appropriately in the following line.
      - KAFKA_CFG_ADVERTISED_LISTENERS=EXTERNAL://ec2-E-F-G-H.us-east-1.compute.amazonaws.com:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=EXTERNAL
    depends_on:
      - zookeeper